### ISSUE TITLE
Spacy 3.3.0

### ISSUE THREAD

**Issue by rociolangoo** [upunaprosk/grammar_checker#1]
Hey! I am trying to retrain the model in the latest version of SpaCy to speed up the time it takes to display the results.
But for some reason, I'm not being able to do it. Do you plan to update it?

Thank u so much, love ur work!

**Comment by upunaprosk** [comment]
Hi,
Thank you for reaching out;
I have recently retrained the model with the latest SpaCy v. 3.5.0!

The checker consists of 6 pipelines=6 Transformer models that can sometimes cause a response delay. 
A model with six Transformer models performs better than one Transformer fine-tuned on the mixed range of errors.
I have also added an example for retraining [here](https://github.com/upunaprosk/grammar-checker/blob/master/Retrain_example.ipynb).

**Comment by rociolangoo** [comment]
Thank u! That was really useful.

I wanted to take this opportunity to ask you how could I add to the training the part of the corpus annotations that include the error correction. 
This way the model will highlight on text the errors with tags, and will be able to offer suggestions also.

**Comment by upunaprosk** [comment]
Hi!
You need a generative model for suggesting corrections,
I think generative models are not yet supported by spaCy
